name: "LiteSQL Release"

on:
    push:
        tags:
            - "litesql/v*"

env:
    PROJ_PATH: LiteSql/LiteSql.csproj

jobs:
    deploy:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build VersionS
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - run: dotnet restore ${{ env.PROJ_PATH}}
            - run: dotnet build ${{ env.PROJ_PATH}} -c Release  --no-restore
            - run: dotnet publish ${{ env.PROJ_PATH}} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true

