name: "LiteSQL Release"

on:
    push:
        tags:
            - "litesql/v*"

env:
    PROJ_PATH: LiteSql/LiteSql.csproj

jobs:
    deploy:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Versions
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - run: dotnet build ${{ env.PROJ_PATH}} -c Release
            - run: dotnet publish ${{ env.PROJ_PATH}} -c Release -r win-x64
            - run: zip -r test.zip bin/Release/net8.0-windows/win-x64 -j
            
            - name: Create Release
              uses: actions/create-release@v1
              id: create_release
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                tag_name: ${{ github.ref }}
                release_name: ${{ github.ref }}

            - name: Upload Assets to Release Page
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
              with:
                upload_url: ${{steps.create_release.outputs.upload_url}}
                asset_path: LiteSql/bin/Release/net8.0-windows/win-x64/
                asset_name: test.zip
                asset_content_type:  application/zip

